repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.5.0
   hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: check-ast
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.0
  hooks:
    - id: nbqa-black
      args: [--line-length=72]
    - id: nbqa-flake8
      args: ["--nbqa-diff"]
